In [1]:
import re
import pymorphy3
import pandas as pd
from sklearn.model_selection import train_test_split
from razdel import tokenize
from navec import Navec
import numpy as np
from math import log
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
seed = 42
np.random.seed(seed)

# 1. Загружаем датасет
Возьмём его часть (половину)

In [3]:
ds = pd.read_csv(r'../../data/petitions.csv')

In [4]:
ds.head()

        id                               public_petition_text  reason_category
0  3168490                                     снег на дороге  Благоустройство
1  3219678                очистить кабельный киоск от рекламы  Благоустройство
2  2963920  Просим убрать все деревья и кустарники, которы...  Благоустройство
3  3374910  Неудовлетворительное состояние парадной - надп...   Содержание МКД
4  3336285                                           Граффити  Благоустройство

In [5]:
ds = ds.drop(columns=['id'], axis=1)

In [6]:
ds['reason_category'].value_counts()

reason_category
Благоустройство                                                                     34769
Содержание МКД                                                                      14461
Нарушение правил пользования общим имуществом                                        2170
Незаконная информационная и (или) рекламная конструкция                              1831
Фасад                                                                                1483
Повреждения или неисправность элементов уличной инфраструктуры                       1164
Кровля                                                                                825
Водоснабжение                                                                         809
Состояние рекламных или информационных конструкций                                    673
Санитарное состояние                                                                  434
Центральное отопление                                                                 284
Подвалы                                                                               254
Незаконная реализация товаров с торгового оборудования (прилавок, ящик, с земли)      251
Нарушение порядка пользования общим имуществом                                        243
Водоотведение                                                                         238
Name: count, dtype: int64

In [7]:
top_classes = ds['reason_category'].value_counts().head(2).index

frames = []
for cls, group in ds.groupby('reason_category'):
    if cls in top_classes:
        group = group.sample(frac=0.3, random_state=42)  # оставить половину
    frames.append(group)

ds_sample = pd.concat(frames)

In [8]:
ds_sample['reason_category'].value_counts()

reason_category
Благоустройство                                                                     10431
Содержание МКД                                                                       4338
Нарушение правил пользования общим имуществом                                        2170
Незаконная информационная и (или) рекламная конструкция                              1831
Фасад                                                                                1483
Повреждения или неисправность элементов уличной инфраструктуры                       1164
Кровля                                                                                825
Водоснабжение                                                                         809
Состояние рекламных или информационных конструкций                                    673
Санитарное состояние                                                                  434
Центральное отопление                                                                 284
Подвалы                                                                               254
Незаконная реализация товаров с торгового оборудования (прилавок, ящик, с земли)      251
Нарушение порядка пользования общим имуществом                                        243
Водоотведение                                                                         238
Name: count, dtype: int64

In [9]:
ds_sample.head()

                                    public_petition_text  reason_category
57338                                     упавшее дерево  Благоустройство
21420                          Повреждена решетка стока.  Благоустройство
39101  Неубранный  снег на проезжей части и там, где ...  Благоустройство
7870   Прошу установить по лежачему полицейскому с ка...  Благоустройство
42523                               объявления на знаках  Благоустройство

# 2. Выполним предобработку данных

In [10]:
ds_sample['public_petition_text'] = ds_sample['public_petition_text'].map(lambda x: re.sub(r'[^а-яё\s]', '', x, flags=re.IGNORECASE))

In [11]:
ds_sample['public_petition_text'] = ds_sample['public_petition_text'].map(lambda x: x.lower())

In [12]:
ds_sample['public_petition_text'] = ds_sample['public_petition_text'].map(lambda x: re.sub(r'\s+', ' ', x).strip())

In [13]:
ds_sample['public_petition_text'] = ds_sample['public_petition_text'].map(lambda x: '\n'.join([line.strip() for line in x.split('\n')]))

In [14]:
ds_sample.head()

                                    public_petition_text  reason_category
57338                                     упавшее дерево  Благоустройство
21420                           повреждена решетка стока  Благоустройство
39101  неубранный снег на проезжей части и там где па...  Благоустройство
7870   прошу установить по лежачему полицейскому с ка...  Благоустройство
42523                               объявления на знаках  Благоустройство

In [15]:
def get_tokens(string):
    tokens = list(tokenize(string))
    return [_.text for _ in tokens]

In [16]:
ds_sample['public_petition_text'] = ds_sample['public_petition_text'].map(lambda x: get_tokens(x))

In [17]:
ds_sample.head()

                                    public_petition_text  reason_category
57338                                  [упавшее, дерево]  Благоустройство
21420                       [повреждена, решетка, стока]  Благоустройство
39101  [неубранный, снег, на, проезжей, части, и, там...  Благоустройство
7870   [прошу, установить, по, лежачему, полицейскому...  Благоустройство
42523                           [объявления, на, знаках]  Благоустройство

In [18]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Denis\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Denis\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [19]:
stop_words = set(stopwords.words('russian'))

In [20]:
def delete_stopwords(tokens):
    return [w for w in tokens if w.isalpha() and w not in stop_words]

In [21]:
ds_sample['public_petition_text'] = ds_sample['public_petition_text'].map(lambda x: delete_stopwords(x))

In [22]:
ds_sample.head()

                                    public_petition_text  reason_category
57338                                  [упавшее, дерево]  Благоустройство
21420                       [повреждена, решетка, стока]  Благоустройство
39101  [неубранный, снег, проезжей, части, паркуются,...  Благоустройство
7870   [прошу, установить, лежачему, полицейскому, ка...  Благоустройство
42523                               [объявления, знаках]  Благоустройство

In [23]:
morph = pymorphy3.MorphAnalyzer()
def lemmatize_words(words: list) -> list:
    return [morph.parse(word)[0].normal_form for word in words]

In [24]:
ds_sample['public_petition_text'] = ds_sample['public_petition_text'].map(lambda x: lemmatize_words(x))

In [25]:
ds_sample.head()

                                    public_petition_text  reason_category
57338                                  [упавший, дерево]  Благоустройство
21420                         [повредить, решётка, сток]  Благоустройство
39101  [неубранный, снег, проезжий, часть, парковатьс...  Благоустройство
7870   [просить, установить, лежачий, полицейский, ка...  Благоустройство
42523                                 [объявление, знак]  Благоустройство

In [26]:
tfidf_vectorizer = TfidfVectorizer()
ds_sample['public_petition_text'] = ds_sample['public_petition_text'].map(lambda x: ' '.join(x))

In [27]:
ds_sample.head()

                                    public_petition_text  reason_category
57338                                     упавший дерево  Благоустройство
21420                             повредить решётка сток  Благоустройство
39101  неубранный снег проезжий часть парковаться авт...  Благоустройство
7870   просить установить лежачий полицейский каждый ...  Благоустройство
42523                                    объявление знак  Благоустройство

In [28]:
X_tfidf = tfidf_vectorizer.fit_transform(ds_sample['public_petition_text'])

In [29]:
df_tfidf = pd.DataFrame(X_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())
df_tfidf.head()

,аа,аао,ааш,аба,абз,абп,абразивный,абрамов,абсолютно,абсолютный,...,яхтенный,ячеистый,ячейка,ящик,ящикитребоваться,ящикпогнутый,ёж,ёлка,ёлочный,ёмкость
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
X = df_tfidf
y = ds_sample['reason_category']

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

# Обучим модель

In [32]:
from catboost import CatBoostClassifier
from sklearn.metrics import classification_report, accuracy_score

In [33]:
unique, counts = np.unique(y_train, return_counts=True)
total = len(y_train)
class_weights = [total / (len(unique) * count) for count in counts]

In [36]:
model = CatBoostClassifier(
    iterations=1000,             # больше итераций + ранняя остановка
    learning_rate=0.03,          # чуть меньше для стабильности
    depth=8,                     # немного глубже, чтобы уловить сложные паттерны
    l2_leaf_reg=5,               # регуляризация (можно 3–10 подбирать)
    border_count=128,            # повышает качество на сложных фичах
    loss_function='MultiClass',  
    class_weights=class_weights, # важно при дисбалансе!
    random_seed=42,
    early_stopping_rounds=50,    # чтобы не переобучаться
    eval_metric='TotalF1',       # лучше отражает баланс Precision/Recall
    task_type='CPU',             # 'GPU' если доступна видеокарта
    bootstrap_type='Bayesian',   # стабилизирует обучение
    bagging_temperature=0.8,     # усиливает рандомизацию деревьев
    grow_policy='Lossguide',     # адаптивное разрастание деревьев
    min_data_in_leaf=20          # ограничивает переобучение на малых классах
)

In [37]:
model.fit(X_train, y_train)

0:	learn: 0.2471947	total: 561ms	remaining: 9m 20s
1:	learn: 0.2992518	total: 1.04s	remaining: 8m 41s
2:	learn: 0.2987849	total: 1.5s	remaining: 8m 19s
3:	learn: 0.3639534	total: 1.97s	remaining: 8m 11s
4:	learn: 0.4084020	total: 2.43s	remaining: 8m 4s
5:	learn: 0.4625654	total: 2.93s	remaining: 8m 5s
6:	learn: 0.4752528	total: 3.43s	remaining: 8m 6s
7:	learn: 0.4762539	total: 3.87s	remaining: 8m
8:	learn: 0.4809305	total: 4.37s	remaining: 8m 1s
9:	learn: 0.5060087	total: 4.82s	remaining: 7m 57s
10:	learn: 0.5169934	total: 5.32s	remaining: 7m 58s
11:	learn: 0.5578296	total: 5.82s	remaining: 7m 58s
12:	learn: 0.5772909	total: 6.29s	remaining: 7m 57s
13:	learn: 0.5765557	total: 6.78s	remaining: 7m 57s
14:	learn: 0.5786220	total: 7.29s	remaining: 7m 58s
15:	learn: 0.5825027	total: 7.79s	remaining: 7m 58s
16:	learn: 0.6005155	total: 8.31s	remaining: 8m
17:	learn: 0.6268666	total: 8.83s	remaining: 8m 1s
18:	learn: 0.6391177	total: 9.27s	remaining: 7m 58s
19:	learn: 0.6477712	total: 9.68s	remaining: 7m 54s
20:	learn: 0.6772925	total: 10.2s	remaining: 7m 55s
21:	learn: 0.6808944	total: 10.7s	remaining: 7m 56s
22:	learn: 0.6815208	total: 11.2s	remaining: 7m 57s
23:	learn: 0.6767083	total: 11.7s	remaining: 7m 54s
24:	learn: 0.6764892	total: 12.2s	remaining: 7m 54s
25:	learn: 0.6849779	total: 12.6s	remaining: 7m 53s
26:	learn: 0.6941383	total: 13.1s	remaining: 7m 51s
27:	learn: 0.6932492	total: 13.6s	remaining: 7m 51s
28:	learn: 0.6944507	total: 14.1s	remaining: 7m 51s
29:	learn: 0.6952878	total: 14.6s	remaining: 7m 51s
30:	learn: 0.6956421	total: 15.1s	remaining: 7m 51s
31:	learn: 0.6967213	total: 15.6s	remaining: 7m 50s
32:	learn: 0.6966624	total: 16s	remaining: 7m 49s
33:	learn: 0.7044464	total: 16.6s	remaining: 7m 50s
34:	learn: 0.7082159	total: 17.1s	remaining: 7m 50s
35:	learn: 0.7088887	total: 17.5s	remaining: 7m 49s
36:	learn: 0.7084921	total: 18s	remaining: 7m 49s
37:	learn: 0.7094847	total: 18.5s	remaining: 7m 47s
38:	learn: 0.7096425	total: 18.9s	remaining: 7m 46s
39:	learn: 0.7081317	total: 19.4s	remaining: 7m 45s
40:	learn: 0.7081024	total: 19.9s	remaining: 7m 45s
41:	learn: 0.7136457	total: 20.4s	remaining: 7m 44s
42:	learn: 0.7239768	total: 20.8s	remaining: 7m 43s
43:	learn: 0.7240941	total: 21.3s	remaining: 7m 43s
44:	learn: 0.7248650	total: 21.8s	remaining: 7m 42s
45:	learn: 0.7248475	total: 22.3s	remaining: 7m 41s
46:	learn: 0.7283819	total: 22.7s	remaining: 7m 41s
47:	learn: 0.7286783	total: 23.2s	remaining: 7m 39s
48:	learn: 0.7256348	total: 23.8s	remaining: 7m 41s
49:	learn: 0.7284702	total: 24.4s	remaining: 7m 43s
50:	learn: 0.7277659	total: 24.9s	remaining: 7m 43s
51:	learn: 0.7274576	total: 25.4s	remaining: 7m 43s
52:	learn: 0.7287086	total: 25.9s	remaining: 7m 43s
53:	learn: 0.7285955	total: 26.4s	remaining: 7m 41s
54:	learn: 0.7285282	total: 26.8s	remaining: 7m 40s
55:	learn: 0.7292459	total: 27.3s	remaining: 7m 39s
56:	learn: 0.7321928	total: 27.8s	remaining: 7m 39s
57:	learn: 0.7339230	total: 28.2s	remaining: 7m 38s
58:	learn: 0.7341143	total: 28.7s	remaining: 7m 37s
59:	learn: 0.7362200	total: 29.2s	remaining: 7m 37s
60:	learn: 0.7363749	total: 29.6s	remaining: 7m 36s
61:	learn: 0.7413089	total: 30.1s	remaining: 7m 35s
62:	learn: 0.7426740	total: 30.6s	remaining: 7m 35s
63:	learn: 0.7419011	total: 31.1s	remaining: 7m 35s
64:	learn: 0.7422995	total: 31.6s	remaining: 7m 34s
65:	learn: 0.7438744	total: 32s	remaining: 7m 33s
66:	learn: 0.7435243	total: 32.5s	remaining: 7m 32s
67:	learn: 0.7436611	total: 33s	remaining: 7m 32s
68:	learn: 0.7439623	total: 33.5s	remaining: 7m 31s
69:	learn: 0.7439870	total: 33.9s	remaining: 7m 30s
70:	learn: 0.7455978	total: 34.4s	remaining: 7m 30s
71:	learn: 0.7450663	total: 34.9s	remaining: 7m 29s
72:	learn: 0.7466460	total: 35.4s	remaining: 7m 29s
73:	learn: 0.7460805	total: 35.9s	remaining: 7m 28s
74:	learn: 0.7472576	total: 36.3s	remaining: 7m 27s
75:	learn: 0.7476903	total: 36.8s	remaining: 7m 27s
76:	learn: 0.7483418	total: 37.3s	remaining: 7m 27s
77:	learn: 0.7483802	total: 37.8s	remaining: 7m 27s
78:	learn: 0.7500065	total: 38.2s	remaining: 7m 25s
79:	learn: 0.7504918	total: 38.7s	remaining: 7m 24s
80:	learn: 0.7508181	total: 39.1s	remaining: 7m 24s
81:	learn: 0.7522178	total: 39.6s	remaining: 7m 23s
82:	learn: 0.7525475	total: 40.1s	remaining: 7m 23s
83:	learn: 0.7543874	total: 40.6s	remaining: 7m 23s
84:	learn: 0.7578007	total: 41.1s	remaining: 7m 22s
85:	learn: 0.7583806	total: 41.6s	remaining: 7m 22s
86:	learn: 0.7582863	total: 42.1s	remaining: 7m 21s
87:	learn: 0.7582949	total: 42.5s	remaining: 7m 20s
88:	learn: 0.7588083	total: 43s	remaining: 7m 20s
89:	learn: 0.7583662	total: 43.5s	remaining: 7m 20s
90:	learn: 0.7584966	total: 44s	remaining: 7m 19s
91:	learn: 0.7587288	total: 44.4s	remaining: 7m 18s
92:	learn: 0.7589335	total: 44.9s	remaining: 7m 17s
93:	learn: 0.7612350	total: 45.4s	remaining: 7m 17s
94:	learn: 0.7624834	total: 45.8s	remaining: 7m 16s
95:	learn: 0.7630112	total: 46.2s	remaining: 7m 15s
96:	learn: 0.7629281	total: 46.7s	remaining: 7m 14s
97:	learn: 0.7641062	total: 47.2s	remaining: 7m 14s
98:	learn: 0.7650820	total: 47.7s	remaining: 7m 13s
99:	learn: 0.7654434	total: 48.1s	remaining: 7m 13s
100:	learn: 0.7654989	total: 48.6s	remaining: 7m 12s
101:	learn: 0.7660081	total: 49.1s	remaining: 7m 12s
102:	learn: 0.7668855	total: 49.6s	remaining: 7m 11s
103:	learn: 0.7658844	total: 50.1s	remaining: 7m 11s
104:	learn: 0.7659082	total: 50.5s	remaining: 7m 10s
105:	learn: 0.7665614	total: 51s	remaining: 7m 10s
106:	learn: 0.7669921	total: 51.5s	remaining: 7m 9s
107:	learn: 0.7677758	total: 52s	remaining: 7m 9s
108:	learn: 0.7689329	total: 52.5s	remaining: 7m 8s
109:	learn: 0.7690939	total: 52.9s	remaining: 7m 8s
110:	learn: 0.7687194	total: 53.4s	remaining: 7m 7s
111:	learn: 0.7698959	total: 53.9s	remaining: 7m 7s
112:	learn: 0.7693778	total: 54.3s	remaining: 7m 6s
113:	learn: 0.7693591	total: 54.8s	remaining: 7m 5s
114:	learn: 0.7690873	total: 55.3s	remaining: 7m 5s
115:	learn: 0.7700969	total: 55.8s	remaining: 7m 5s
116:	learn: 0.7704282	total: 56.2s	remaining: 7m 4s
117:	learn: 0.7703795	total: 56.7s	remaining: 7m 3s
118:	learn: 0.7707407	total: 57.2s	remaining: 7m 3s
119:	learn: 0.7721970	total: 57.6s	remaining: 7m 2s
120:	learn: 0.7738763	total: 58.1s	remaining: 7m 1s
121:	learn: 0.7739556	total: 58.6s	remaining: 7m 1s
122:	learn: 0.7740949	total: 59.1s	remaining: 7m 1s
123:	learn: 0.7753789	total: 59.5s	remaining: 7m
124:	learn: 0.7754800	total: 1m	remaining: 7m
125:	learn: 0.7774125	total: 1m	remaining: 6m 59s
126:	learn: 0.7787098	total: 1m	remaining: 6m 59s
127:	learn: 0.7804272	total: 1m 1s	remaining: 6m 58s
128:	learn: 0.7830241	total: 1m 1s	remaining: 6m 58s
129:	learn: 0.7837397	total: 1m 2s	remaining: 6m 57s
130:	learn: 0.7839815	total: 1m 2s	remaining: 6m 57s
131:	learn: 0.7851659	total: 1m 3s	remaining: 6m 56s
132:	learn: 0.7844562	total: 1m 3s	remaining: 6m 55s
133:	learn: 0.7847166	total: 1m 4s	remaining: 6m 55s
134:	learn: 0.7851695	total: 1m 4s	remaining: 6m 54s
135:	learn: 0.7856602	total: 1m 5s	remaining: 6m 54s
136:	learn: 0.7856952	total: 1m 5s	remaining: 6m 53s
137:	learn: 0.7858049	total: 1m 6s	remaining: 6m 53s
138:	learn: 0.7867059	total: 1m 6s	remaining: 6m 52s
139:	learn: 0.7874970	total: 1m 7s	remaining: 6m 51s
140:	learn: 0.7881060	total: 1m 7s	remaining: 6m 51s
141:	learn: 0.7877405	total: 1m 7s	remaining: 6m 50s
142:	learn: 0.7883751	total: 1m 8s	remaining: 6m 50s
143:	learn: 0.7891125	total: 1m 8s	remaining: 6m 49s
144:	learn: 0.7898890	total: 1m 9s	remaining: 6m 48s
145:	learn: 0.7901949	total: 1m 9s	remaining: 6m 48s
146:	learn: 0.7901992	total: 1m 10s	remaining: 6m 47s
147:	learn: 0.7909155	total: 1m 10s	remaining: 6m 46s
148:	learn: 0.7910154	total: 1m 11s	remaining: 6m 46s
149:	learn: 0.7909697	total: 1m 11s	remaining: 6m 45s
150:	learn: 0.7914179	total: 1m 12s	remaining: 6m 45s
151:	learn: 0.7919516	total: 1m 12s	remaining: 6m 44s
152:	learn: 0.7927845	total: 1m 12s	remaining: 6m 43s
153:	learn: 0.7925923	total: 1m 13s	remaining: 6m 43s
154:	learn: 0.7925166	total: 1m 13s	remaining: 6m 42s
155:	learn: 0.7923305	total: 1m 14s	remaining: 6m 41s
156:	learn: 0.7936865	total: 1m 14s	remaining: 6m 41s
157:	learn: 0.7945858	total: 1m 15s	remaining: 6m 40s
158:	learn: 0.7968503	total: 1m 15s	remaining: 6m 40s
159:	learn: 0.7977150	total: 1m 16s	remaining: 6m 39s
160:	learn: 0.7974931	total: 1m 16s	remaining: 6m 39s
161:	learn: 0.7975189	total: 1m 17s	remaining: 6m 38s
162:	learn: 0.7983669	total: 1m 17s	remaining: 6m 37s
163:	learn: 0.7986645	total: 1m 17s	remaining: 6m 37s
164:	learn: 0.7993947	total: 1m 18s	remaining: 6m 36s
165:	learn: 0.8012162	total: 1m 18s	remaining: 6m 36s
166:	learn: 0.8014064	total: 1m 19s	remaining: 6m 35s
167:	learn: 0.8015989	total: 1m 19s	remaining: 6m 35s
168:	learn: 0.8019881	total: 1m 20s	remaining: 6m 34s
169:	learn: 0.8023232	total: 1m 20s	remaining: 6m 34s
170:	learn: 0.8015659	total: 1m 21s	remaining: 6m 33s
171:	learn: 0.8021562	total: 1m 21s	remaining: 6m 33s
172:	learn: 0.8030235	total: 1m 22s	remaining: 6m 32s
173:	learn: 0.8030862	total: 1m 22s	remaining: 6m 32s
174:	learn: 0.8032375	total: 1m 23s	remaining: 6m 31s
175:	learn: 0.8036817	total: 1m 23s	remaining: 6m 31s
176:	learn: 0.8058427	total: 1m 23s	remaining: 6m 30s
177:	learn: 0.8055392	total: 1m 24s	remaining: 6m 29s
178:	learn: 0.8069991	total: 1m 24s	remaining: 6m 29s
179:	learn: 0.8076299	total: 1m 25s	remaining: 6m 28s
180:	learn: 0.8082454	total: 1m 25s	remaining: 6m 28s
181:	learn: 0.8077414	total: 1m 26s	remaining: 6m 27s
182:	learn: 0.8081158	total: 1m 26s	remaining: 6m 26s
183:	learn: 0.8095839	total: 1m 27s	remaining: 6m 26s
184:	learn: 0.8096451	total: 1m 27s	remaining: 6m 25s
185:	learn: 0.8097417	total: 1m 27s	remaining: 6m 25s
186:	learn: 0.8095290	total: 1m 28s	remaining: 6m 24s
187:	learn: 0.8115528	total: 1m 28s	remaining: 6m 24s
188:	learn: 0.8121175	total: 1m 29s	remaining: 6m 23s
189:	learn: 0.8122227	total: 1m 29s	remaining: 6m 22s
190:	learn: 0.8128324	total: 1m 30s	remaining: 6m 22s
191:	learn: 0.8123972	total: 1m 30s	remaining: 6m 21s
192:	learn: 0.8124106	total: 1m 31s	remaining: 6m 21s
193:	learn: 0.8130167	total: 1m 31s	remaining: 6m 20s
194:	learn: 0.8136149	total: 1m 32s	remaining: 6m 20s
195:	learn: 0.8148204	total: 1m 32s	remaining: 6m 19s
196:	learn: 0.8154506	total: 1m 33s	remaining: 6m 19s
197:	learn: 0.8158727	total: 1m 33s	remaining: 6m 18s
198:	learn: 0.8157120	total: 1m 33s	remaining: 6m 17s
199:	learn: 0.8161069	total: 1m 34s	remaining: 6m 17s
200:	learn: 0.8167175	total: 1m 34s	remaining: 6m 16s
201:	learn: 0.8170280	total: 1m 35s	remaining: 6m 16s
202:	learn: 0.8185854	total: 1m 35s	remaining: 6m 15s
203:	learn: 0.8188576	total: 1m 36s	remaining: 6m 15s
204:	learn: 0.8192950	total: 1m 36s	remaining: 6m 14s
205:	learn: 0.8189693	total: 1m 37s	remaining: 6m 14s
206:	learn: 0.8193655	total: 1m 37s	remaining: 6m 13s
207:	learn: 0.8192658	total: 1m 37s	remaining: 6m 12s
208:	learn: 0.8193562	total: 1m 38s	remaining: 6m 12s
209:	learn: 0.8196465	total: 1m 38s	remaining: 6m 11s
210:	learn: 0.8200662	total: 1m 39s	remaining: 6m 10s
211:	learn: 0.8202093	total: 1m 39s	remaining: 6m 10s
212:	learn: 0.8205841	total: 1m 40s	remaining: 6m 9s
213:	learn: 0.8205267	total: 1m 40s	remaining: 6m 9s
214:	learn: 0.8207345	total: 1m 40s	remaining: 6m 8s
215:	learn: 0.8210890	total: 1m 41s	remaining: 6m 7s
216:	learn: 0.8212415	total: 1m 41s	remaining: 6m 7s
217:	learn: 0.8215903	total: 1m 42s	remaining: 6m 6s
218:	learn: 0.8214371	total: 1m 42s	remaining: 6m 6s
219:	learn: 0.8217517	total: 1m 43s	remaining: 6m 5s
220:	learn: 0.8217114	total: 1m 43s	remaining: 6m 5s
221:	learn: 0.8229063	total: 1m 44s	remaining: 6m 4s
222:	learn: 0.8226044	total: 1m 44s	remaining: 6m 3s
223:	learn: 0.8230474	total: 1m 44s	remaining: 6m 3s
224:	learn: 0.8228447	total: 1m 45s	remaining: 6m 2s
225:	learn: 0.8227369	total: 1m 45s	remaining: 6m 2s
226:	learn: 0.8229166	total: 1m 46s	remaining: 6m 1s
227:	learn: 0.8239292	total: 1m 46s	remaining: 6m 1s
228:	learn: 0.8246206	total: 1m 47s	remaining: 6m
229:	learn: 0.8256265	total: 1m 47s	remaining: 6m
230:	learn: 0.8257688	total: 1m 48s	remaining: 5m 59s
231:	learn: 0.8257545	total: 1m 48s	remaining: 5m 59s
232:	learn: 0.8265027	total: 1m 48s	remaining: 5m 58s
233:	learn: 0.8267853	total: 1m 49s	remaining: 5m 58s
234:	learn: 0.8272119	total: 1m 49s	remaining: 5m 57s
235:	learn: 0.8276285	total: 1m 50s	remaining: 5m 57s
236:	learn: 0.8278070	total: 1m 50s	remaining: 5m 56s
237:	learn: 0.8279306	total: 1m 51s	remaining: 5m 55s
238:	learn: 0.8284106	total: 1m 51s	remaining: 5m 55s
239:	learn: 0.8286507	total: 1m 52s	remaining: 5m 54s
240:	learn: 0.8283979	total: 1m 52s	remaining: 5m 54s
241:	learn: 0.8286025	total: 1m 53s	remaining: 5m 54s
242:	learn: 0.8291750	total: 1m 53s	remaining: 5m 53s
243:	learn: 0.8290914	total: 1m 53s	remaining: 5m 53s
244:	learn: 0.8295752	total: 1m 54s	remaining: 5m 52s
245:	learn: 0.8297140	total: 1m 54s	remaining: 5m 52s
246:	learn: 0.8301138	total: 1m 55s	remaining: 5m 51s
247:	learn: 0.8302144	total: 1m 55s	remaining: 5m 51s
248:	learn: 0.8304254	total: 1m 56s	remaining: 5m 50s
249:	learn: 0.8305814	total: 1m 56s	remaining: 5m 49s
250:	learn: 0.8311882	total: 1m 57s	remaining: 5m 49s
251:	learn: 0.8314028	total: 1m 57s	remaining: 5m 48s
252:	learn: 0.8315090	total: 1m 57s	remaining: 5m 48s
253:	learn: 0.8318501	total: 1m 58s	remaining: 5m 47s
254:	learn: 0.8322406	total: 1m 58s	remaining: 5m 47s
255:	learn: 0.8326855	total: 1m 59s	remaining: 5m 46s
256:	learn: 0.8328910	total: 1m 59s	remaining: 5m 45s
257:	learn: 0.8330739	total: 2m	remaining: 5m 45s
258:	learn: 0.8326898	total: 2m	remaining: 5m 45s
259:	learn: 0.8327008	total: 2m 1s	remaining: 5m 44s
260:	learn: 0.8336350	total: 2m 1s	remaining: 5m 43s
261:	learn: 0.8337813	total: 2m 1s	remaining: 5m 43s
262:	learn: 0.8335888	total: 2m 2s	remaining: 5m 42s
263:	learn: 0.8338720	total: 2m 2s	remaining: 5m 42s
264:	learn: 0.8341881	total: 2m 3s	remaining: 5m 41s
265:	learn: 0.8341998	total: 2m 3s	remaining: 5m 41s
266:	learn: 0.8348409	total: 2m 4s	remaining: 5m 40s
267:	learn: 0.8349540	total: 2m 4s	remaining: 5m 39s
268:	learn: 0.8361861	total: 2m 4s	remaining: 5m 39s
269:	learn: 0.8360906	total: 2m 5s	remaining: 5m 38s
270:	learn: 0.8362098	total: 2m 5s	remaining: 5m 38s
271:	learn: 0.8368800	total: 2m 6s	remaining: 5m 37s
272:	learn: 0.8372750	total: 2m 6s	remaining: 5m 37s
273:	learn: 0.8374697	total: 2m 7s	remaining: 5m 36s
274:	learn: 0.8374982	total: 2m 7s	remaining: 5m 36s
275:	learn: 0.8371577	total: 2m 7s	remaining: 5m 35s
276:	learn: 0.8375017	total: 2m 8s	remaining: 5m 34s
277:	learn: 0.8379142	total: 2m 8s	remaining: 5m 34s
278:	learn: 0.8382956	total: 2m 9s	remaining: 5m 33s
279:	learn: 0.8383642	total: 2m 9s	remaining: 5m 32s
280:	learn: 0.8384498	total: 2m 9s	remaining: 5m 32s
281:	learn: 0.8384576	total: 2m 10s	remaining: 5m 31s
282:	learn: 0.8386991	total: 2m 10s	remaining: 5m 31s
283:	learn: 0.8387779	total: 2m 11s	remaining: 5m 30s
284:	learn: 0.8402395	total: 2m 11s	remaining: 5m 30s
285:	learn: 0.8409800	total: 2m 11s	remaining: 5m 29s
286:	learn: 0.8410541	total: 2m 12s	remaining: 5m 28s
287:	learn: 0.8411288	total: 2m 12s	remaining: 5m 28s
288:	learn: 0.8411556	total: 2m 13s	remaining: 5m 27s
289:	learn: 0.8416143	total: 2m 13s	remaining: 5m 27s
290:	learn: 0.8416977	total: 2m 14s	remaining: 5m 26s
291:	learn: 0.8418961	total: 2m 14s	remaining: 5m 25s
292:	learn: 0.8421783	total: 2m 14s	remaining: 5m 25s
293:	learn: 0.8426303	total: 2m 15s	remaining: 5m 24s
294:	learn: 0.8425704	total: 2m 15s	remaining: 5m 23s
295:	learn: 0.8423311	total: 2m 15s	remaining: 5m 23s
296:	learn: 0.8425693	total: 2m 16s	remaining: 5m 22s
297:	learn: 0.8428617	total: 2m 16s	remaining: 5m 22s
298:	learn: 0.8422336	total: 2m 17s	remaining: 5m 21s
299:	learn: 0.8424373	total: 2m 17s	remaining: 5m 21s
300:	learn: 0.8432808	total: 2m 18s	remaining: 5m 20s
301:	learn: 0.8438874	total: 2m 18s	remaining: 5m 20s
302:	learn: 0.8444747	total: 2m 18s	remaining: 5m 19s
303:	learn: 0.8450188	total: 2m 19s	remaining: 5m 19s
304:	learn: 0.8449741	total: 2m 19s	remaining: 5m 18s
305:	learn: 0.8451890	total: 2m 20s	remaining: 5m 18s
306:	learn: 0.8451890	total: 2m 20s	remaining: 5m 17s
307:	learn: 0.8452369	total: 2m 21s	remaining: 5m 17s
308:	learn: 0.8452520	total: 2m 21s	remaining: 5m 16s
309:	learn: 0.8453709	total: 2m 22s	remaining: 5m 16s
310:	learn: 0.8453733	total: 2m 22s	remaining: 5m 15s
311:	learn: 0.8446883	total: 2m 22s	remaining: 5m 15s
312:	learn: 0.8456600	total: 2m 23s	remaining: 5m 14s
313:	learn: 0.8456951	total: 2m 23s	remaining: 5m 14s
314:	learn: 0.8448816	total: 2m 24s	remaining: 5m 13s
315:	learn: 0.8458352	total: 2m 24s	remaining: 5m 13s
316:	learn: 0.8458380	total: 2m 25s	remaining: 5m 12s
317:	learn: 0.8457914	total: 2m 25s	remaining: 5m 12s
318:	learn: 0.8456838	total: 2m 25s	remaining: 5m 11s
319:	learn: 0.8451304	total: 2m 26s	remaining: 5m 10s
320:	learn: 0.8458578	total: 2m 26s	remaining: 5m 10s
321:	learn: 0.8459813	total: 2m 27s	remaining: 5m 9s
322:	learn: 0.8463368	total: 2m 27s	remaining: 5m 9s
323:	learn: 0.8472106	total: 2m 28s	remaining: 5m 8s
324:	learn: 0.8473342	total: 2m 28s	remaining: 5m 8s
325:	learn: 0.8473880	total: 2m 28s	remaining: 5m 7s
326:	learn: 0.8474473	total: 2m 29s	remaining: 5m 7s
327:	learn: 0.8475552	total: 2m 29s	remaining: 5m 7s
328:	learn: 0.8479598	total: 2m 30s	remaining: 5m 6s
329:	learn: 0.8479643	total: 2m 30s	remaining: 5m 5s
330:	learn: 0.8476730	total: 2m 30s	remaining: 5m 4s
331:	learn: 0.8476730	total: 2m 31s	remaining: 5m 3s
332:	learn: 0.8477018	total: 2m 31s	remaining: 5m 3s
333:	learn: 0.8478890	total: 2m 31s	remaining: 5m 2s
334:	learn: 0.8478647	total: 2m 32s	remaining: 5m 2s
335:	learn: 0.8478122	total: 2m 32s	remaining: 5m 1s
336:	learn: 0.8479676	total: 2m 33s	remaining: 5m 1s
337:	learn: 0.8483664	total: 2m 33s	remaining: 5m
338:	learn: 0.8484377	total: 2m 33s	remaining: 5m
339:	learn: 0.8485547	total: 2m 34s	remaining: 4m 59s
340:	learn: 0.8486314	total: 2m 34s	remaining: 4m 58s
341:	learn: 0.8486940	total: 2m 35s	remaining: 4m 58s
342:	learn: 0.8490994	total: 2m 35s	remaining: 4m 57s
343:	learn: 0.8489876	total: 2m 35s	remaining: 4m 57s
344:	learn: 0.8490711	total: 2m 36s	remaining: 4m 56s
345:	learn: 0.8491951	total: 2m 36s	remaining: 4m 55s
346:	learn: 0.8494050	total: 2m 37s	remaining: 4m 55s
347:	learn: 0.8494183	total: 2m 37s	remaining: 4m 55s
348:	learn: 0.8495720	total: 2m 38s	remaining: 4m 54s
349:	learn: 0.8493904	total: 2m 38s	remaining: 4m 54s
350:	learn: 0.8495496	total: 2m 38s	remaining: 4m 53s
351:	learn: 0.8497864	total: 2m 39s	remaining: 4m 53s
352:	learn: 0.8499473	total: 2m 39s	remaining: 4m 52s
353:	learn: 0.8500908	total: 2m 39s	remaining: 4m 51s
354:	learn: 0.8500908	total: 2m 40s	remaining: 4m 51s
355:	learn: 0.8501398	total: 2m 40s	remaining: 4m 50s
356:	learn: 0.8502846	total: 2m 40s	remaining: 4m 49s
357:	learn: 0.8503019	total: 2m 41s	remaining: 4m 49s
358:	learn: 0.8504512	total: 2m 41s	remaining: 4m 48s
359:	learn: 0.8506594	total: 2m 42s	remaining: 4m 48s
360:	learn: 0.8507326	total: 2m 42s	remaining: 4m 48s
361:	learn: 0.8507440	total: 2m 43s	remaining: 4m 47s
362:	learn: 0.8517140	total: 2m 43s	remaining: 4m 46s
363:	learn: 0.8516976	total: 2m 43s	remaining: 4m 45s
364:	learn: 0.8520827	total: 2m 43s	remaining: 4m 45s
365:	learn: 0.8525336	total: 2m 44s	remaining: 4m 44s
366:	learn: 0.8523115	total: 2m 44s	remaining: 4m 44s
367:	learn: 0.8526297	total: 2m 45s	remaining: 4m 43s
368:	learn: 0.8527279	total: 2m 45s	remaining: 4m 43s
369:	learn: 0.8528253	total: 2m 45s	remaining: 4m 42s
370:	learn: 0.8529882	total: 2m 46s	remaining: 4m 41s
371:	learn: 0.8529842	total: 2m 46s	remaining: 4m 41s
372:	learn: 0.8530950	total: 2m 46s	remaining: 4m 40s
373:	learn: 0.8532235	total: 2m 47s	remaining: 4m 39s
374:	learn: 0.8537314	total: 2m 47s	remaining: 4m 39s
375:	learn: 0.8537154	total: 2m 48s	remaining: 4m 39s
376:	learn: 0.8537212	total: 2m 48s	remaining: 4m 38s

In [38]:
pred = model.predict(X_test)

In [39]:
print("Точность:", accuracy_score(y_test, pred))
print("\nОтчёт классификации:\n", classification_report(y_test, pred))

Точность: 0.7990562327959103

Отчёт классификации:
                                                                                   precision    recall  f1-score   support

                                                                 Благоустройство       0.89      0.75      0.81      2086
                                                                   Водоотведение       0.82      0.85      0.83        47
                                                                   Водоснабжение       0.79      0.83      0.81       162
                                                                          Кровля       0.77      0.88      0.82       165
                                  Нарушение порядка пользования общим имуществом       0.45      0.88      0.60        48
                                   Нарушение правил пользования общим имуществом       0.97      0.87      0.92       434
                         Незаконная информационная и (или) рекламная конструкция       0.81      0.90      0.85       366
Незаконная реализация товаров с торгового оборудования (прилавок, ящик, с земли)       0.98      1.00      0.99        50
                  Повреждения или неисправность элементов уличной инфраструктуры       0.88      0.89      0.88       233
                                                                         Подвалы       0.58      0.98      0.73        51
                                                            Санитарное состояние       0.80      0.89      0.84        87
                                                                  Содержание МКД       0.83      0.78      0.80       868
                              Состояние рекламных или информационных конструкций       0.30      0.80      0.44       135
                                                                           Фасад       0.66      0.76      0.71       297
                                                           Центральное отопление       0.76      0.84      0.80        57

                                                                        accuracy                           0.80      5086
                                                                       macro avg       0.75      0.86      0.79      5086
                                                                    weighted avg       0.83      0.80      0.81      5086